### PR TITLE
WIP: Adds devices existence checks before using

### PR DESCRIPTION
**Pull request by frenck**
Check devices if they exist before actually using them.

This allows an add-on developer to specify devices that might not be available on all platforms.
For example: We could add the Raspberry camera device to the SSH add-on, without breaking it on other platforms.

Fixes: #656
Ref: #184

### CODE REVIEW

**Comment by pvizeli** [comment]
That don't work because, the supervisor run without any privileged.

You need go the way with hardware.py and /sys/ or /prog/

**Comment by frenck** [comment]
🤦‍♂️ 

Will revisit it. Meanwhile, I'll add the 🚧 WIP tag.

**Comment by pvizeli** [comment]
Small input, maybe we can use the `machine` tag. Like we do on audio to resolve the name of input. I think we need also add a functionality that you can add a config option like `machine: [rpi]` and this can only be installed on a rpi platform.

**Comment by frenck** [comment]
I'm closing this PR. It has to be rewritten anyway and I'm short on time as well.

**Pull request closed without merging**
