### PR TITLE
Update Home-Assistant 0.53.0

### PR DESCRIPTION
**Pull request by herbalizer404**

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @herbalizer404, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;hassio#183).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by herbalizer404** [comment]
Someone to merge? Please

**Comment by gollo** [comment]
I can't merge, but don't the docker images have to be there first?

**Comment by herbalizer404** [comment]
You're right, but the docker image is available. Thank you, I noticed I've to change 0.53.0 in 0.53.

**Comment by herbalizer404** [comment]
My mistake, I was on the wrong repo. still not available on homeassistant/raspberrypi3-homeassistant :(

**Comment by pvizeli** [comment]
Yeah we need first build all images. Actual the armhf vuild are very slow and we need a armhf build server soon to speedup this process

**Comment by herbalizer404** [comment]
Ok, thank you. It's working like a charm now.

**Pull request closed without merging**
