### PR TITLE
Adapt regex validation to allow docker images from other registries

### PR DESCRIPTION
**Pull request by sholzmayer**
fixes issue #564

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @sholzmayer, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;hassio#608).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by homeassistant** [comment]
Hi @sholzmayer, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;hassio#608).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by homeassistant** [comment]
Hi @sholzmayer, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;hassio#608).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by pvizeli** [comment]
Yeah I'm fine to support other registrar. Your change the regex of repository and they don't support any character, that is wrong. You need group it in three parts: (optional: registar/)(repository)/(image)

https://docs.docker.com/engine/reference/commandline/tag/#tag-an-image-referenced-by-name-and-tag

**Comment by frenck** [comment]
Most registries support multiple levels nowadays.

For example: gitlab.com/<repository>/<arch>/<image>
Or: gitlab.com/<repository>/<arch>/<beta>/<image>

DockerHub always lacks behind their own specs 😢

**Comment by sholzmayer** [comment]
I did some adaptions to the regex, so this is my proposal: https://regex101.com/r/lumTPS/1/

**Pull request merged**
