### PR TITLE
fix: use a different convention to handle multiple devices on same card

### PR DESCRIPTION
**Pull request by luca-simonetti**
issue #472

### CODE REVIEW

**Comment by pvizeli** [comment]
Does the UI work with this?

**Comment by luca-simonetti** [comment]
can you give me instructions on how to build it and test it in  a test environment (not on my raspberry)

**Comment by luca-simonetti** [comment]
I have found myself the hassio-build repo with instructions.

**Comment by luca-simonetti** [comment]
From the addon, all the channels are now correctly shown

screenshot-10 0 0 76-8123-2018 10 19-17-49-51
screenshot-10 0 0 76-8123-2018 10 19-17-49-51 1

This is the new format of the API
screenshot-json parser online fr-2018 10 19-17-53-58

which I think breaks the popup:
screenshot-10 0 0 76-8123-2018 10 19-17-54-49

**Comment by vicfergar** [comment]
Hi @luca-simonetti 
why do you think that your change affects to the popup? It looks like the is a lot of devices connected in this dev environment.. isn't it @pvizeli? Can you check the stable build in this same dev enviroment? Just to compare

Great work with the PR! It looks very promissing!

**Comment by luca-simonetti** [comment]
any update on this?

**Comment by pvizeli** [comment]
I will convert this later into attr but for now it's okay

**Pull request merged**
